import React,{useEffect,useMemo,useState}from"react";
import{Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import ActiveUserBanner from"../../src/components/ActiveUserBanner";
import{CALENDAR_TABS,buildVerifiedCalendarEvents,getCalendarSummary}from"../../src/calendar/calendarHubData";
import{loadCorporateActions}from"../../src/features/corporate-actions/corporateActionStore";
export default function Calendar(){
 const[tab,setTab]=useState("This Month"),[actions,setActions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;loadCorporateActions().then(x=>{if(active)setActions(Array.isArray(x)?x:[])}).catch(e=>{if(active)setError(e?.message||"Verified calendar evidence is unavailable.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const events=useMemo(()=>buildVerifiedCalendarEvents(actions,tab),[actions,tab]),summary=useMemo(()=>getCalendarSummary(events),[events]);
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><Text style={s.title}>Calendar</Text><Text style={s.subtitle}>Verified corporate actions and dated market events.</Text><ActiveUserBanner/><View style={s.tabs}>{CALENDAR_TABS.map(x=><Pressable key={x} style={[s.tab,tab===x&&s.active]} onPress={()=>setTab(x)}><Text style={tab===x?s.activeText:s.tabText}>{x}</Text></Pressable>)}</View><View style={s.summary}><Metric label="Events" value={summary.total}/><Metric label="Dividends" value={summary.dividends}/><Metric label="Deadlines" value={summary.deadlines}/><Metric label="Securities" value={summary.actions}/></View><View style={s.card}><Text style={s.cardTitle}>Verified events</Text>{loading?<Text style={s.body}>Loading verified events…</Text>:null}{!loading&&error?<Text style={s.body}>{error}</Text>:null}{!loading&&!error&&!events.length?<Text style={s.body}>No verified events are available for this period. GateCEP does not display sample dates.</Text>:null}{events.map(e=><View key={e.id} style={s.row}><View style={{flex:1}}><Text style={s.eventTitle}>{e.title}</Text><Text style={s.company}>{e.company}</Text><Text style={s.body}>{e.detail}</Text><Text style={s.source}>{e.source}</Text></View><View><Text style={s.type}>{e.type}</Text><Text style={s.date}>{e.date}</Text></View></View>)}</View><View style={s.policy}><Text style={s.cardTitle}>Evidence policy</Text><Text style={s.body}>Only dated records carrying a verified issuer, exchange, regulator, broker, custodian, manual, or provider reference are displayed.</Text></View></ScrollView>;
}
function Metric({label,value}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#020617"},content:{padding:22,paddingTop:70,paddingBottom:120},title:{color:"white",fontSize:32,fontWeight:"900"},subtitle:{color:"#94a3b8",marginTop:8,lineHeight:22},tabs:{marginTop:20,flexDirection:"row",flexWrap:"wrap",gap:8},tab:{paddingHorizontal:14,paddingVertical:10,borderRadius:14,backgroundColor:"#1e293b"},active:{backgroundColor:"#9333ea"},tabText:{color:"#94a3b8",fontWeight:"900"},activeText:{color:"white",fontWeight:"900"},summary:{marginTop:18,flexDirection:"row",flexWrap:"wrap",gap:10},metric:{width:"47%",backgroundColor:"#0f172a",borderRadius:16,padding:14},metricLabel:{color:"#94a3b8",fontSize:12},metricValue:{color:"white",fontWeight:"900",marginTop:4},card:{marginTop:18,backgroundColor:"#0f172a",borderRadius:20,padding:16},cardTitle:{color:"#67e8f9",fontWeight:"900",fontSize:18},body:{color:"#cbd5e1",marginTop:7,lineHeight:20},row:{flexDirection:"row",gap:12,paddingVertical:14,borderBottomColor:"#1e293b",borderBottomWidth:1},eventTitle:{color:"white",fontWeight:"900"},company:{color:"#67e8f9",marginTop:5},source:{color:"#94a3b8",fontSize:11,marginTop:6},type:{color:"#fbbf24",fontWeight:"900",fontSize:11,textAlign:"right"},date:{color:"white",fontWeight:"900",fontSize:12,marginTop:6},policy:{marginTop:18,padding:16,borderRadius:20,backgroundColor:"rgba(6,182,212,.1)",borderColor:"rgba(6,182,212,.4)",borderWidth:1}});
