import React,{useEffect,useMemo,useState}from"react";
import{Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import ActiveUserBanner from"../../src/components/ActiveUserBanner";
import useMarketData from"../../src/services/markets/useMarketData";
import{loadCorporateActions}from"../../src/features/corporate-actions/corporateActionStore";
import{NEWS_TABS,buildVerifiedNews,getNewsForTab,getNewsSummary}from"../../src/news/newsHubData";
export default function News(){
 const[tab,setTab]=useState("Market"),[actions,setActions]=useState([]);const market=useMarketData();
 useEffect(()=>{let active=true;loadCorporateActions().then(x=>{if(active)setActions(Array.isArray(x)?x:[])}).catch(()=>{if(active)setActions([])});return()=>{active=false}},[]);
 const all=useMemo(()=>buildVerifiedNews({quotes:market.rows,actions,generatedAt:market.lastUpdated,provider:market.provider}),[market.rows,market.lastUpdated,market.provider,actions]),rows=useMemo(()=>getNewsForTab(all,tab),[all,tab]),summary=useMemo(()=>getNewsSummary(all),[all]);
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><Text style={s.title}>News & Insights</Text><Text style={s.subtitle}>Verified market evidence, corporate actions, and clearly labeled Coach G analysis.</Text><ActiveUserBanner/><View style={s.status}><Text style={s.statusTitle}>{market.loading?"Loading verified sources":market.connected?"Verified sources connected":"Verified market source unavailable"}</Text><Text style={s.body}>{market.loading?"Checking the current market snapshot…":market.connected?`${market.rows.length} prices from ${market.provider||"the verified provider"}.`:market.error||"No sample stories are displayed."}</Text></View><View style={s.tabs}>{NEWS_TABS.map(x=><Pressable key={x} style={[s.tab,tab===x&&s.active]} onPress={()=>setTab(x)}><Text style={tab===x?s.activeText:s.tabText}>{x}</Text></Pressable>)}</View><View style={s.summary}><Metric label="Market" value={summary.market}/><Metric label="Company" value={summary.company}/><Metric label="Dividends" value={summary.dividends}/><Metric label="Coach G" value={summary.coachG}/></View><View style={s.card}><Text style={s.cardTitle}>{tab}</Text>{!market.loading&&!rows.length?<Text style={s.body}>No verified {tab.toLowerCase()} items are available. GateCEP does not substitute placeholder news.</Text>:null}{rows.map(x=><View key={x.id} style={s.row}><View style={s.top}><Text style={s.category}>{x.category}</Text><Text style={s.date}>{x.date||"Date unavailable"}</Text></View><Text style={s.newsTitle}>{x.symbol} · {x.title}</Text><Text style={s.source}>{x.source}</Text><Text style={s.body}>{x.detail}</Text></View>)}</View></ScrollView>;
}
function Metric({label,value}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#020617"},content:{padding:22,paddingTop:70,paddingBottom:120},title:{color:"white",fontSize:32,fontWeight:"900"},subtitle:{color:"#94a3b8",marginTop:8,lineHeight:22},status:{marginTop:18,padding:16,borderRadius:20,backgroundColor:"rgba(6,182,212,.10)",borderColor:"rgba(6,182,212,.4)",borderWidth:1},statusTitle:{color:"#67e8f9",fontWeight:"900",fontSize:17},body:{color:"#cbd5e1",marginTop:7,lineHeight:20},tabs:{marginTop:20,flexDirection:"row",flexWrap:"wrap",gap:8},tab:{paddingHorizontal:14,paddingVertical:10,borderRadius:14,backgroundColor:"#1e293b"},active:{backgroundColor:"#9333ea"},tabText:{color:"#94a3b8",fontWeight:"900"},activeText:{color:"white",fontWeight:"900"},summary:{marginTop:18,flexDirection:"row",flexWrap:"wrap",gap:10},metric:{width:"47%",backgroundColor:"#0f172a",borderRadius:16,padding:14},metricLabel:{color:"#94a3b8",fontSize:12},metricValue:{color:"white",fontWeight:"900",marginTop:4},card:{marginTop:18,backgroundColor:"#0f172a",borderRadius:20,padding:16},cardTitle:{color:"#67e8f9",fontWeight:"900",fontSize:18},row:{paddingVertical:14,borderBottomWidth:1,borderBottomColor:"#1e293b"},top:{flexDirection:"row",justifyContent:"space-between",gap:10},category:{color:"#fbbf24",fontWeight:"900"},date:{color:"#94a3b8",fontSize:12},newsTitle:{color:"white",fontWeight:"900",marginTop:8,lineHeight:21},source:{color:"#67e8f9",marginTop:6,fontSize:12}});
