export const GOAL_PROGRESS_STATUSES=Object.freeze({NOT_ENOUGH_DATA:"NOT_ENOUGH_DATA",AHEAD:"AHEAD",ON_TRACK:"ON_TRACK",SLIGHTLY_BEHIND:"SLIGHTLY_BEHIND",BEHIND:"BEHIND",CRITICAL_GAP:"CRITICAL_GAP",ACHIEVED:"ACHIEVED"});
export const GOAL_ACTION_TYPES=Object.freeze({CONTINUE_PLAN:"CONTINUE_PLAN",INCREASE_CONTRIBUTION:"INCREASE_CONTRIBUTION",REVIEW_ALLOCATION:"REVIEW_ALLOCATION",REVIEW_TIMELINE:"REVIEW_TIMELINE",REVIEW_GOAL:"REVIEW_GOAL",BUILD_CASH_BUFFER:"BUILD_CASH_BUFFER",DISCUSS_WITH_COACH_G:"DISCUSS_WITH_COACH_G"});
const n=v=>v===null||v===undefined||v===""?null:(Number.isFinite(Number(v))?Number(v):null);
const r=(v,d=2)=>n(v)===null?null:Number(Number(v).toFixed(d));
function monthsBetween(a,b){const x=new Date(a),y=new Date(b);if(Number.isNaN(x.getTime())||Number.isNaN(y.getTime()))return null;return Math.max(0,(y.getFullYear()-x.getFullYear())*12+(y.getMonth()-x.getMonth()));}
function fvCurrent(v,mr,m){return m<=0?v:v*Math.pow(1+mr,m);}
function fvContrib(c,mr,m){if(m<=0||c<=0)return 0;if(mr===0)return c*m;return c*((Math.pow(1+mr,m)-1)/mr);}
function requiredContribution(t,v,mr,m){if(m<=0)return t<=v?0:null;const future=fvCurrent(v,mr,m),remain=Math.max(t-future,0);if(remain===0)return 0;if(mr===0)return remain/m;const f=(Math.pow(1+mr,m)-1)/mr;return f>0?remain/f:null;}

export function normalizeInvestorGoal(goal={}){return {id:goal?.id||null,name:goal?.name||goal?.title||"Financial Goal",targetAmount:n(goal?.targetAmount??goal?.targetValue),targetDate:goal?.targetDate||null,priority:goal?.priority||"MEDIUM",currency:goal?.currency||"KES",purpose:goal?.purpose||goal?.description||null};}
export function buildGoalCurrentPosition({portfolio={},cash={},goal={}}={}){const invested=n(portfolio?.currentValue??portfolio?.totalMarketValue??portfolio?.portfolioValue)||0,available=n(cash?.availableCash??portfolio?.availableCash)||0,includeCash=goal?.includeCash!==false;return {investedValue:r(invested),availableCash:r(available),includeCash,currentGoalValue:r(invested+(includeCash?available:0))};}
export function calculateGoalRequiredTrajectory({goal,currentPosition,contributionBehavior={},planningAssumptions={},asOfDate=new Date().toISOString().slice(0,10)}={}){const g=normalizeInvestorGoal(goal),target=g.targetAmount,current=n(currentPosition?.currentGoalValue),months=monthsBetween(asOfDate,g.targetDate),annual=n(planningAssumptions?.annualReturnPercentage)??8,monthlyRate=Math.pow(1+annual/100,1/12)-1,monthly=n(contributionBehavior?.monthlyContribution??contributionBehavior?.averageMonthlyContribution)||0;if(target===null||current===null||months===null)return {valid:false,reason:"Goal target, current value, and target date are required."};const projected=fvCurrent(current,monthlyRate,months)+fvContrib(monthly,monthlyRate,months),required=requiredContribution(target,current,monthlyRate,months);return {valid:true,targetAmount:r(target),currentValue:r(current),monthsRemaining:months,annualReturnAssumption:r(annual),monthlyContribution:r(monthly),requiredMonthlyContribution:r(required),projectedValue:r(projected),projectedGap:r(projected-target),projectedProgressPercentage:target>0?r(projected/target*100):null,currentProgressPercentage:target>0?r(current/target*100):null};}
export function classifyGoalProgress({trajectory}={}){if(!trajectory?.valid)return {status:GOAL_PROGRESS_STATUSES.NOT_ENOUGH_DATA,label:"Not enough data",score:null};if(trajectory.currentValue>=trajectory.targetAmount)return {status:GOAL_PROGRESS_STATUSES.ACHIEVED,label:"Goal achieved",score:100};const q=trajectory.projectedValue/trajectory.targetAmount;if(q>=1.1)return {status:GOAL_PROGRESS_STATUSES.AHEAD,label:"Ahead of plan",score:95};if(q>=0.98)return {status:GOAL_PROGRESS_STATUSES.ON_TRACK,label:"On track",score:85};if(q>=0.90)return {status:GOAL_PROGRESS_STATUSES.SLIGHTLY_BEHIND,label:"Slightly behind",score:70};if(q>=0.75)return {status:GOAL_PROGRESS_STATUSES.BEHIND,label:"Behind plan",score:50};return {status:GOAL_PROGRESS_STATUSES.CRITICAL_GAP,label:"Significant gap",score:25};}
export function analyzeGoalBehaviorAlignment({goal,trajectory,behavior={},portfolioHealth={}}={}){const findings=[],actual=n(behavior?.averageMonthlyContribution)||0,required=n(trajectory?.requiredMonthlyContribution);if(required!==null&&actual<required*.9)findings.push({type:"CONTRIBUTION_GAP",level:"HIGH",message:`Recent contributions average ${goal?.currency||"KES"} ${r(actual)}, below the estimated ${goal?.currency||"KES"} ${r(required)} monthly contribution required by the current plan.`});if(behavior?.highTurnover===true&&(goal?.timeHorizon==="LONG_TERM"||trajectory?.monthsRemaining>=60))findings.push({type:"BEHAVIOR_GOAL_MISMATCH",level:"MEDIUM",message:"Recent trading appears relatively active for a long-term goal. Coach G should understand why before assuming the behavior is inconsistent with the plan."});if(portfolioHealth?.concentrationRisk==="HIGH")findings.push({type:"CONCENTRATION_RISK",level:"HIGH",message:"Portfolio concentration may make progress toward this goal more dependent on a small number of holdings."});if(behavior?.cashBufferConcern===true)findings.push({type:"LIQUIDITY_PRESSURE",level:"HIGH",message:"Cash-flow pressure may interfere with regular investing. Coach G should discuss liquidity before recommending higher contributions."});return {aligned:findings.length===0,findings};}
export function buildGoalNextBestAction({goal,trajectory,classification,alignment}={}){if(classification?.status===GOAL_PROGRESS_STATUSES.ACHIEVED)return {action:GOAL_ACTION_TYPES.REVIEW_GOAL,label:"Celebrate and plan what comes next",reason:"The goal has been achieved. Coach G should help the investor decide what comes next."};if(alignment?.findings?.some(x=>x.type==="LIQUIDITY_PRESSURE"))return {action:GOAL_ACTION_TYPES.BUILD_CASH_BUFFER,label:"Protect your cash position first",reason:"Increasing investment contributions may not be appropriate until short-term liquidity is more comfortable."};if(alignment?.findings?.some(x=>x.type==="CONCENTRATION_RISK"))return {action:GOAL_ACTION_TYPES.REVIEW_ALLOCATION,label:"Review portfolio concentration",reason:"The current goal may depend too heavily on a small number of holdings."};if([GOAL_PROGRESS_STATUSES.BEHIND,GOAL_PROGRESS_STATUSES.CRITICAL_GAP,GOAL_PROGRESS_STATUSES.SLIGHTLY_BEHIND].includes(classification?.status))return {action:GOAL_ACTION_TYPES.INCREASE_CONTRIBUTION,label:"Review your contribution plan",reason:trajectory?.requiredMonthlyContribution!==null?`The current plan estimates about ${goal?.currency||"KES"} ${r(trajectory.requiredMonthlyContribution)} per month may be needed under the present assumptions.`:"The current trajectory is behind the target and should be reviewed with Coach G."};if([GOAL_PROGRESS_STATUSES.AHEAD,GOAL_PROGRESS_STATUSES.ON_TRACK].includes(classification?.status))return {action:GOAL_ACTION_TYPES.CONTINUE_PLAN,label:"Keep doing what is working",reason:"The current trajectory is consistent with the goal. Coach G should focus on maintaining discipline and avoiding unnecessary risk."};return {action:GOAL_ACTION_TYPES.DISCUSS_WITH_COACH_G,label:"Review this goal with Coach G",reason:"GateCEP needs more context before recommending a change."};}
export function buildGoalProgressNarrative({goal,trajectory,classification,alignment,nextBestAction}={}){if(!trajectory?.valid)return `Coach G needs a little more information before judging progress toward ${goal?.name||"this goal"}.`;const gap=trajectory.projectedGap>=0?`${goal?.currency||"KES"} ${r(trajectory.projectedGap)} above the target`:`${goal?.currency||"KES"} ${Math.abs(r(trajectory.projectedGap))} below the target`;return `You are currently ${classification?.label||"being assessed"} for ${goal?.name||"this goal"}. Under the current assumptions, your projected value is ${goal?.currency||"KES"} ${r(trajectory.projectedValue)}, which is ${gap}. ${alignment?.aligned?"Your recent behavior does not currently show a major mismatch with this goal.":`GateCEP found ${alignment?.findings?.length||0} behavior or portfolio issue(s) worth discussing.`} Coach G's next step is: ${nextBestAction?.label||"review the plan"}.`;}
export function buildInvestorGoalProgress({goal,portfolio={},cash={},contributionBehavior={},behavior={},portfolioHealth={},investorDNA={},planningAssumptions={},asOfDate=new Date().toISOString().slice(0,10)}={}){const g=normalizeInvestorGoal(goal),currentPosition=buildGoalCurrentPosition({portfolio,cash,goal}),trajectory=calculateGoalRequiredTrajectory({goal:g,currentPosition,contributionBehavior,planningAssumptions,asOfDate}),classification=classifyGoalProgress({trajectory}),alignment=analyzeGoalBehaviorAlignment({goal:{...g,timeHorizon:goal?.timeHorizon},trajectory,behavior,portfolioHealth}),nextBestAction=buildGoalNextBestAction({goal:g,trajectory,classification,alignment,investorDNA});return {generatedAt:new Date().toISOString(),goal:g,currentPosition,trajectory,classification,alignment,nextBestAction,coachGContext:{shouldExplain:true,shouldAskInvestor:classification.status===GOAL_PROGRESS_STATUSES.NOT_ENOUGH_DATA||alignment.aligned===false,narrative:buildGoalProgressNarrative({goal:g,trajectory,classification,alignment,nextBestAction})},safeguards:{advisoryOnly:true,goalChanged:false,portfolioChanged:false,contributionChanged:false}};}
export function buildInvestorGoalProgressBatch({goals=[],...context}={}){const rank={HIGH:3,MEDIUM:2,LOW:1};return (Array.isArray(goals)?goals:[]).map(goal=>buildInvestorGoalProgress({goal,...context})).sort((a,b)=>(rank[b?.goal?.priority]||0)-(rank[a?.goal?.priority]||0));}
export function loadGoalsNeedingCoachGAttention({goals=[],...context}={}){return buildInvestorGoalProgressBatch({goals,...context}).filter(x=>[GOAL_PROGRESS_STATUSES.CRITICAL_GAP,GOAL_PROGRESS_STATUSES.BEHIND,GOAL_PROGRESS_STATUSES.SLIGHTLY_BEHIND].includes(x?.classification?.status)||x?.alignment?.aligned===false);}
