export const PORTFOLIO_EVENT_TYPES = {
  BROKER_SYNC:
    "BROKER_SYNC",

  BROKER_IMPORT:
    "BROKER_IMPORT",

  BUY_ORDER:
    "BUY_ORDER",

  SELL_ORDER:
    "SELL_ORDER",

  DIVIDEND_RECEIVED:
    "DIVIDEND_RECEIVED",

  BONUS_SHARE:
    "BONUS_SHARE",

  STOCK_SPLIT:
    "STOCK_SPLIT",

  RIGHTS_ISSUE:
    "RIGHTS_ISSUE",

  TRANSFER_IN:
    "TRANSFER_IN",

  TRANSFER_OUT:
    "TRANSFER_OUT",

  CASH_DEPOSIT:
    "CASH_DEPOSIT",

  CASH_WITHDRAWAL:
    "CASH_WITHDRAWAL",

  BROKER_FEE:
    "BROKER_FEE",

  TAX:
    "TAX",

  PORTFOLIO_ADJUSTMENT:
    "PORTFOLIO_ADJUSTMENT"
};

export const PORTFOLIO_EVENT_CATEGORIES = {
  BROKER:
    "BROKER",

  TRADE:
    "TRADE",

  INCOME:
    "INCOME",

  CASH:
    "CASH",

  CORPORATE_ACTION:
    "CORPORATE_ACTION",

  ADJUSTMENT:
    "ADJUSTMENT"
};

export function getPortfolioEventCategory(
  eventType
) {
  switch (eventType) {
    case PORTFOLIO_EVENT_TYPES.BROKER_SYNC:
    case PORTFOLIO_EVENT_TYPES.BROKER_IMPORT:
      return PORTFOLIO_EVENT_CATEGORIES.BROKER;

    case PORTFOLIO_EVENT_TYPES.BUY_ORDER:
    case PORTFOLIO_EVENT_TYPES.SELL_ORDER:
      return PORTFOLIO_EVENT_CATEGORIES.TRADE;

    case PORTFOLIO_EVENT_TYPES.DIVIDEND_RECEIVED:
      return PORTFOLIO_EVENT_CATEGORIES.INCOME;

    case PORTFOLIO_EVENT_TYPES.CASH_DEPOSIT:
    case PORTFOLIO_EVENT_TYPES.CASH_WITHDRAWAL:
    case PORTFOLIO_EVENT_TYPES.BROKER_FEE:
    case PORTFOLIO_EVENT_TYPES.TAX:
      return PORTFOLIO_EVENT_CATEGORIES.CASH;

    case PORTFOLIO_EVENT_TYPES.BONUS_SHARE:
    case PORTFOLIO_EVENT_TYPES.STOCK_SPLIT:
    case PORTFOLIO_EVENT_TYPES.RIGHTS_ISSUE:
      return PORTFOLIO_EVENT_CATEGORIES.CORPORATE_ACTION;

    default:
      return PORTFOLIO_EVENT_CATEGORIES.ADJUSTMENT;
  }
}