#!/usr/bin/env bash
set -euo pipefail
ROOT="$(pwd)"
FILE="$ROOT/mobile/app/(tabs)/trading.js"

echo "PC-030M20AQ3 — Trading / Decision Lab UI Consolidation (M20AR4-compatible verifier v3)"
[[ -f "$FILE" ]] || { echo "FAIL — missing $FILE"; exit 1; }

python - "$ROOT" "$FILE" <<'PY'
from pathlib import Path
import re, sys
root = Path(sys.argv[1])
path = Path(sys.argv[2])
s = path.read_text(encoding="utf-8")

assert "PC-030M20AQ3 UI consolidation" in s, "M20AQ3 marker missing"
assert "PC-030M20AQ2 Decision Lab Home" in s or "COACH G DECISION CONVERSATION" in s, "Decision Lab component missing"

legacy_entry = "Simulate a Buy" in s and "Simulate a Sell" in s
conversation_entry = all(x in s for x in [
    "I have a decision",
    "What if I add money?",
    "Explore a security idea",
    "Explore a reduction / sell",
])
assert legacy_entry or conversation_entry, "Decision Lab entry controls missing"

assert "Review Goal & Recovery Context" in s, "goal/recovery context link missing"

# M20AR formats the route object compactly (`mode:\"BROKER_PLAN\"`), while older
# revisions used spaces (`mode: \"BROKER_PLAN\"`). Verify the semantic contract,
# not whitespace generated by a patch.
broker_plan_handoff = bool(re.search(r'mode\s*:\s*["\']BROKER_PLAN["\']', s))
assert broker_plan_handoff, "Broker Action Plan handoff missing"
assert "basket-execution" in s, "Broker Action Plan destination missing"
assert "Review Broker Action Plan" in s, "Broker Action Plan investor-facing control missing"
assert "loadTradingHubData" in s, "Trading data service integration was removed"

start = s.find("<ScrollView", s.find("export default function Trading"))
close = s.find("</ScrollView>", start)
assert start >= 0 and close > start, "Trading main ScrollView not found"
main = s[start:close]

active = main.find("<ActiveUserBanner")
# M20AR4 adds entryParams to DecisionLabHome so recovery context can continue
# in the same conversation. Verify component placement semantically rather than
# depending on an exact JSX prop list or whitespace.
decision_match = re.search(r'<DecisionLabHome\b[^>]*\bdata\s*=\s*\{data\}[^>]*/?>', main)
decision = decision_match.start() if decision_match else -1
assert active >= 0 and decision >= 0, "Active Account / Decision Lab render missing"
assert active < decision, "Active Account is not above Decision Lab"
assert "Broker Evidence" not in main, "Broker Evidence label is still rendered"
assert "Broker controlled" not in main, "Broker controlled card is still rendered"
assert "Read-only broker account, order, depth, and execution evidence." not in main, "obsolete subtitle remains"
assert "Test investment decisions against your portfolio, goals and risk before you act." in main, "Decision Lab subtitle not updated"

required_routes = [
    root / "mobile/app/broker-accounts.js",
    root / "mobile/app/broker-profile.js",
    root / "mobile/app/portfolio-sync-center.js",
]
missing = [str(p.relative_to(root)) for p in required_routes if not p.exists()]
assert not missing, "dedicated broker support route(s) missing: " + ", ".join(missing)

print("PASS — Active Account is above Coach G Decision Lab.")
print("PASS — obsolete broker-evidence subtitle is gone.")
print("PASS — duplicate Broker Evidence / broker-control UI remains removed from Trading.")
if conversation_entry:
    print("PASS — M20AR conversation entries supersede the old BUY/SELL landing buttons without removing simulation access.")
else:
    print("PASS — original Decision Lab BUY/SELL entry controls remain available.")
print("PASS — goal/recovery context link remains intact.")
print("PASS — Broker Action Plan handoff is present and preserves BROKER_PLAN context.")
print("PASS — broker support is preserved through dedicated routes/services.")
PY

if [[ -f mobile/scripts/test-pc030m20aq-coach-g-decision-lab.mjs ]]; then
  node mobile/scripts/test-pc030m20aq-coach-g-decision-lab.mjs
fi

if [[ -f scripts/verify-pc030m20ap-trade-lab-broker-plan-boundary.sh ]]; then
  echo "Running M20AP regression if present..."
  bash scripts/verify-pc030m20ap-trade-lab-broker-plan-boundary.sh
fi

echo "PC-030M20AQ3 verification complete."
